version: '3.8'

services:
    nginx:
        image: tiangolo/nginx-rtmp
        ports:
            - "1935:1935"
            - "8080:8080"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - devstream
    app:
        build:
            args:
                user: devstream
                uid: 1000
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - devstream
networks:
    devstream:
        driver: bridge
